# Generated by Django 6.0 on 2025-12-30 09:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_material_file_upload_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.IntegerField(choices=[(1, 'Cơ bản'), (2, 'Trung cấp'), (3, 'Nâng cao')], default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.IntegerField(choices=[(1, 'Giáo trình'), (2, 'Slide bài giảng'), (3, 'Video'), (4, 'Tài liệu tham khảo'), (5, 'Khác')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(default=3, limit_choices_to={'role__in': [1, 2]}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='material',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='materials', to='courses.topic'),
        ),
    ]
