# Generated by Django 6.0 on 2025-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_topic_remove_material_file_upload_material_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.IntegerField(choices=[(1, 'Giáo trình'), (2, 'Slide'), (3, 'Video'), (4, 'Tham khảo'), (5, 'Khác')], default=2),
        ),
    ]
